// Variables for Networking

/*
variable "enable_network" {
    type = "string"
    description = "Enable Network Setup"
    default = "true"
}

variable "lab_name" {
    description = "The name of the lab. Used as freeform tag and in other settings."
}

variable "students" {
    description = "The number of student environments needed for the lab."
    default = "1"
}
# variable "tenancy_ocid" {
#     description = "The tenancy OCID."
# }

variable "top_compartment_id" {
    description = "The top level compartment used by the lab."
}
variable "id_padding" {
    description = "The amount of padding added to the student index number to get student id."
    default = "100"
}

variable "subnet_cidr" {
    description = "CIDR for the Private Subnet"
    default     = "10.0.0.0/26"
}

variable "lab_compartment_ids" {
    description = "List of lab compartment ids. This is generated by the admin sub-module."
}
*/